/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROXY_H_RPCGEN
#define _PROXY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define MESSAGEPROG 99
#define MESSAGEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PROXYSERVER 1
extern  char ** proxyserver_1(char **, CLIENT *);
extern  char ** proxyserver_1_svc(char **, struct svc_req *);
extern int messageprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PROXYSERVER 1
extern  char ** proxyserver_1();
extern  char ** proxyserver_1_svc();
extern int messageprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROXY_H_RPCGEN */
